{{- if not .Values.gateway.external }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "pm-backend.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pm-backend.name" . }}
    helm.sh/chart: {{ include "pm-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: http
      protocol: HTTP
      port: 8000
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}
