apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "pm-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pm-backend.name" . }}
    helm.sh/chart: {{ include "pm-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.gateway.external }}
    cluster: {{ .Values.gateway.external.clusterLabel }}
    {{- end }}
spec:
  parentRefs:
    {{- if .Values.gateway.external }}
    - name: {{ .Values.gateway.external.gatewayName }}
      namespace: {{ .Values.gateway.external.gatewayNamespace }}
    {{- else }}
    - name: {{ include "pm-backend.fullname" . }}-gateway
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- if .Values.gateway.host }}
  hostnames:
    - {{ .Values.gateway.host }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "pm-backend.fullname" . }}
          port: 3000
