apiVersion: v1
kind: Service
metadata:
  name: {{ include "pm-backend.fullname" . }}-minio
  labels:
    app.kubernetes.io/name: {{ include "pm-backend.name" . }}-minio
    helm.sh/chart: {{ include "pm-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
    - port: 9001
      targetPort: console
      protocol: TCP
      name: console
  selector:
    app.kubernetes.io/name: {{ include "pm-backend.name" . }}-minio
    app.kubernetes.io/instance: {{ .Release.Name }}
