apiVersion: v1
kind: Service
metadata:
  name: {{ include "puhatak-backend.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: {{ include "puhatak-backend.name" . }}-postgres
    helm.sh/chart: {{ include "puhatak-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: {{ include "puhatak-backend.name" . }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
