apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "puhatak-backend.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: {{ include "puhatak-backend.name" . }}-postgres
    helm.sh/chart: {{ include "puhatak-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "puhatak-backend.name" . }}-postgres
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "puhatak-backend.name" . }}-postgres
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: postgres
          image: "postgres:15-alpine"
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.database }}
            - name: POSTGRES_USER
              value: {{ .Values.db.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.db.username }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.db.username }}
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "puhatak-backend.fullname" . }}-postgres-data
