apiVersion: v1
kind: Secret
metadata:
  name: {{ include "puhatak-backend.fullname" . }}-rails-credentials
  labels:
    app.kubernetes.io/name: {{ include "puhatak-backend.name" . }}
    helm.sh/chart: {{ include "puhatak-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  production.yml.enc: {{ .Values.credentials.productionYmlEnc | b64enc }}
  production.key: {{ .Values.credentials.productionKey | b64enc }}
