---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "pm-backend.fullname" . }}-minio-stripprefix
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pm-backend.name" . }}
    helm.sh/chart: {{ include "pm-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  stripPrefix:
    prefixes:
      - /minio
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "pm-backend.fullname" . }}-limit-body-size
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pm-backend.name" . }}
    helm.sh/chart: {{ include "pm-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  buffering:
    maxRequestBodyBytes: 10485760  # 10MB
