---
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: pm
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pm_dev
    ports:
      - "5432:5432"
  redis:
    image: redis:8.0-alpine
    restart: always
    ports:
      - "6379:6379"
