export const styles = {
  card: {
    background: '#fff',
    border: '1px solid #e0e0e0',
    borderRadius: 8,
    padding: '12px 16px',
    cursor: 'pointer',
    transition: 'box-shadow 0.2s',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  cardHover: {
    boxShadow: '0 1px 2px 0 rgba(60,64,67,0.3), 0 1px 3px 1px rgba(60,64,67,0.15)',
  },
  cardHighlighted: {
    border: '2px solid #f59e0b',
    background: '#fffbeb',
  },
  title: {
    fontSize: 15,
    fontWeight: 500,
    color: '#202124',
    margin: 0,
    lineHeight: 1.4,
  },
  body: {
    fontSize: 13,
    color: '#5f6368',
    margin: 0,
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap',
    overflow: 'hidden',
    display: '-webkit-box',
    WebkitLineClamp: 5,
    WebkitBoxOrient: 'vertical',
  },
  pointsList: {
    display: 'flex',
    flexDirection: 'column',
    margin: '4px 0',
  },
  pointItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    padding: '3px 0',
    fontSize: 13,
    color: '#202124',
    lineHeight: 1.4,
  },
  checkbox: {
    width: 16,
    height: 16,
    border: '2px solid #5f6368',
    borderRadius: 2,
    flexShrink: 0,
    marginTop: 1,
  },
  pointText: {
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  tagsRow: {
    display: 'flex',
    gap: 4,
    flexWrap: 'wrap',
    marginTop: 4,
  },
  tag: {
    fontSize: 11,
    padding: '2px 8px',
    borderRadius: 12,
    background: '#e8eaed',
    color: '#3c4043',
    fontWeight: 500,
  },
};
