default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: puhatak_dev
  username: puhatak
  password: password
  host: localhost

test:
  <<: *default
  database: puhatak_test
  username: puhatak
  password: password
  host: localhost

production:
  <<: *default
  database: puhatak_production
  username: puhatak
  password: <%= ENV["NALKA_DATABASE_PASSWORD"] %>
