default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: pm_dev
    username: pm
    password: password
    host: localhost
  queue:
    <<: *default
    database: pm_dev_queue
    username: pm
    password: password
    host: localhost
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: pm_test
    username: pm
    password: password
    host: localhost
  queue:
    <<: *default
    database: pm_test_queue
    username: pm
    password: password
    host: localhost
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *default
    database: pm_production
    username: pm
    password: <%= ENV["NALKA_DATABASE_PASSWORD"] %>
  queue:
    <<: *default
    database: pm_production_queue
    username: pm
    password: <%= ENV["NALKA_DATABASE_PASSWORD"] %>
